name: Update Sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * *
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Generate Sponsors ðŸ’–
        uses: JamesIves/github-sponsors-readme-action@v1
        if: github.repository == 'Rollczi/LiteCommands'
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          template: <a href="https://github.com/{{{ login }}}"><img src="https://images.weserv.nl/?url=https://github.com/{{{ login }}}.png?v=4&mask=circle" width="60px" alt="{{{ name }}}" /></a>&nbsp;&nbsp;&nbsp;

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.repository == 'Rollczi/LiteCommands'
        with:
          commit-message: Update Sponsors in README.md
          branch: master
          folder: '.'
