name: Update Sponsors
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Generate Sponsors ğŸ’–
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          template: <a href="https://github.com/{{{ login }}}"><img src="https://images.weserv.nl/?url=https://github.com/{{{ login }}}.png?v=4&mask=circle" width="60px" alt="{{{ name }}}" /></a>&nbsp;&nbsp;&nbsp;

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          commit-message: Update Sponsors in README.md
          branch: master
          folder: '.'
